# Generated by Django 3.2.9 on 2021-11-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='gaseosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('light', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
