# Generated by Django 3.2.9 on 2021-11-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBebidas', '0002_alter_cerveza_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaseosa',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vino',
            name='capacidad',
            field=models.IntegerField(),
        ),
    ]
